{:valid? false,
 :error
 "java.util.concurrent.ExecutionException: java.lang.AssertionError: Assert failed: runs\n at java.util.concurrent.FutureTask.report (FutureTask.java:122)\n    java.util.concurrent.FutureTask.get (FutureTask.java:192)\n    clojure.core$deref_future.invoke (core.clj:2186)\n    clojure.core$future_call$reify__6736.deref (core.clj:6683)\n    clojure.core$deref.invoke (core.clj:2206)\n    clojure.core$map$fn__4553.invoke (core.clj:2624)\n    clojure.lang.LazySeq.sval (LazySeq.java:40)\n    clojure.lang.LazySeq.seq (LazySeq.java:56)\n    clojure.lang.RT.seq (RT.java:507)\n    clojure.core/seq (core.clj:137)\n    clojure.core.protocols$seq_reduce.invoke (protocols.clj:30)\n    clojure.core.protocols/fn (protocols.clj:101)\n    clojure.core.protocols$fn__6452$G__6447__6465.invoke (protocols.clj:13)\n    clojure.core$reduce.invoke (core.clj:6519)\n    clojure.core$into.invoke (core.clj:6600)\n    jepsen.checker$compose$reify__7213.check (checker.clj:247)\n    jepsen.checker$check_safe.invoke (checker.clj:36)\n    jepsen.core$run_BANG_$fn__7420.invoke (core.clj:410)\n    jepsen.core$run_BANG_.invoke (core.clj:362)\n    jepsen.aurora_test/fn (aurora_test.clj:11)\n    clojure.test$test_var$fn__7670.invoke (test.clj:704)\n    clojure.test$test_var.invoke (test.clj:704)\n    clojure.test$test_vars$fn__7692$fn__7697.invoke (test.clj:722)\n    clojure.test$default_fixture.invoke (test.clj:674)\n    clojure.test$test_vars$fn__7692.invoke (test.clj:722)\n    clojure.test$default_fixture.invoke (test.clj:674)\n    clojure.test$test_vars.invoke (test.clj:718)\n    clojure.test$test_all_vars.invoke (test.clj:728)\n    clojure.test$test_ns.invoke (test.clj:747)\n    clojure.core$map$fn__4553.invoke (core.clj:2624)\n    clojure.lang.LazySeq.sval (LazySeq.java:40)\n    clojure.lang.LazySeq.seq (LazySeq.java:49)\n    clojure.lang.Cons.next (Cons.java:39)\n    clojure.lang.RT.boundedLength (RT.java:1735)\n    clojure.lang.RestFn.applyTo (RestFn.java:130)\n    clojure.core$apply.invoke (core.clj:632)\n    clojure.test$run_tests.doInvoke (test.clj:762)\n    clojure.lang.RestFn.applyTo (RestFn.java:137)\n    clojure.core$apply.invoke (core.clj:630)\n    user$eval85$fn__140$fn__171.invoke (form-init7742842619303803294.clj:1)\n    user$eval85$fn__140$fn__141.invoke (form-init7742842619303803294.clj:1)\n    user$eval85$fn__140.invoke (form-init7742842619303803294.clj:1)\n    user$eval85.invoke (form-init7742842619303803294.clj:1)\n    clojure.lang.Compiler.eval (Compiler.java:6782)\n    clojure.lang.Compiler.eval (Compiler.java:6772)\n    clojure.lang.Compiler.load (Compiler.java:7227)\n    clojure.lang.Compiler.loadFile (Compiler.java:7165)\n    clojure.main$load_script.invoke (main.clj:275)\n    clojure.main$init_opt.invoke (main.clj:280)\n    clojure.main$initialize.invoke (main.clj:308)\n    clojure.main$null_opt.invoke (main.clj:343)\n    clojure.main$main.doInvoke (main.clj:421)\n    clojure.lang.RestFn.invoke (RestFn.java:421)\n    clojure.lang.Var.invoke (Var.java:383)\n    clojure.lang.AFn.applyToHelper (AFn.java:156)\n    clojure.lang.Var.applyTo (Var.java:700)\n    clojure.main.main (main.java:37)\nCaused by: java.lang.AssertionError: Assert failed: runs\n at jepsen.aurora.checker$checker$reify__8456.check (checker.clj:321)\n    jepsen.checker$compose$reify__7213$fn__7215.invoke (checker.clj:246)\n    clojure.core$pmap$fn__6744$fn__6745.invoke (core.clj:6729)\n    clojure.core$binding_conveyor_fn$fn__4444.invoke (core.clj:1916)\n    clojure.lang.AFn.call (AFn.java:18)\n    java.util.concurrent.FutureTask.run (FutureTask.java:266)\n    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)\n    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)\n    java.lang.Thread.run (Thread.java:745)\n"}
